version: '3'
services:
 db:
  image: mariadb:10.6
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD=toor
   - MYSQL_PASSWORD=P@ssw0rd
   - MYSQL_DATABASE=nextcloud
   - MYSQL_USER=nextcloud
  network_mode: "host"
 app:
  image: nextcloud
  restart: always
  environment:
   - MYSQL_PASSWORD=P@ssw0rd
   - MYSQL_DATABASE=nextcloud
   - MYSQL_USER=nextcloud
   - MYSQL_HOST=db
  network_mode: "host" 
